version: '2'
services:
  app:
    build:
      context: .
      args:
        app_env: development
    environment:
      DATABASE_HOST: mariadb
      DATABASE_USER: root
      DATABASE_PASSWORD: sandbox
      SMTP_HOST: mailcatcher
      SMTP_PORT: 1025
    ports:
      - "3000:3000"
    command: rails s -b 0.0.0.0 -p 3000
    volumes:
      - .:/usr/local/sandbox
    links:
      - mariadb
      - mailcatcher
  mariadb:
    image: mariadb:10.2
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    ports:
      - "13306:3306"
    environment:
      MYSQL_USER: sandbox
      MYSQL_PASSWORD: sandbox
      MYSQL_ROOT_PASSWORD: sandbox
    volumes:
      - rocket-mariadb:/var/lib/mysql
  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
volumes:
  rocket-mariadb: {}
